---
title: "Семинар №1"
author: "Георгий Мороз, Ольга Ляшевская, Илья Щуров, НИУ ВШЭ"
date: "11 ноября 2015"
output:
  knitrBootstrap::bootstrap_document:
    theme.chooser: TRUE
    highlight.chooser: TRUE
    highlight: Xcode
  toc: true
  toc_depth: 4
---

# Семинар №1: базовые возможности R

*Георгий Мороз, Ольга Ляшевская, Илья Щуров, НИУ ВШЭ*

Курс «Анализ лингвистических данных: квантитативные методы и визуализация».

Школа лингвистики НИУ ВШЭ, магистерская программа «Теория языка и компьютерная лингвистика», 2015-16 учебный год.

[Школа лингвистики](http://ling.hse.ru/) | [Все материалы курса](http://hsequantling.wikispaces.com/) | [Исходные коды на Github](https://github.com/ischurov/hsequantling)

<span style='font-size:80%'>Данный материал доступен под лицензией [CC BY-SA
4.0](https://creativecommons.org/licenses/by-sa/4.0/). При использовании обязательно упоминание авторов курса и аффилиации. При наличии технической возможности необходимо также указать активную гиперссылку на [страницу курса](http://hsequantling.wikispaces.com/).<span>

---

# Что обсуждалось на семинаре
- [Конспект семинара Г. Мороза](https://www.getdatajoy.com/project/564328e07882f1fa4140abb3)
- [History семинара И. Щурова](http://pastebin.com/ieeTyxQF)
- См. также конспекты [http://math-info.hse.ru/s14/r/](курса 2014-15 учебного года) для бакалавров: [базовые возможности R](http://rpubs.com/ilyaschurov/lecture1draft) (до раздела «Теория вероятностей в R»), [работа с dataframes, гистограммы, boxplots](http://rpubs.com/ilyaschurov/lecture5). 

# Домашнее задание
## Задача 1
*(По мотивам учебника Gries.)*
Рассмотрим датафрейм, в котором представлены результаты некоторого соревнования. Указать, к каким шкалам относятся переменные, входящие в этот датафрейм.

```{r, bootstrap.show.code=F}
library(knitr)
kable(
  data.frame(
    name=c("John", "Jack", "Kevin", "Weigu"),
    reg_number=c(11,12,8,3),
    country=c("USA", "USA", "UK", "China"),
    place=c(2,3,1,4),
    time=c(10.5, 11.5, 8.3, 13.2)
    )
  )
```

## Задача 2
Создайте вектор, значения которого составляют арифметическую прогрессию от 303 до 1, за исключением тех значений, которые делятся на 4.

**Подсказка:** для вычисления остатка от деления одного числа на другое можно использовать оператор `%%`.

## Задача 3
Создайте вектор, состоящий из квадратов всех чисел от 1 до 100. Выделите из него чётные значения, не меньшие 100 и не большие 1000.

## Задача 4
Загрузите [csv с занятия](http://hsequantling.wikispaces.com/file/view/nanai-vowels.csv/564569635/nanai-vowels.csv) и найдите среднее значение и стандартное отклонение разности первой и второй формант. Постройте гистограмму и ящик с усами для этой разности.

**Подсказки:**

- Не забудьте указать правильное значение параметра `sep` при использовании `read.csv`.
- Для обращения к переменным в датафрейме нужно использовать `$`. 
- Арифметические операции с векторами всегда действуют поэлементно, то есть вектора можно складывать, вычитать, умножать и т.д.
- Гистограмма строится командой `hist`, ящик с усами командой `boxplot`.
